services:

  app:
    build: ./docker/php
    volumes:
      - ./api/web:/work/web

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api/web:/work/web
    depends_on:
      - app

  postgresql:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: posse
      POSTGRES_DB: ph4
    volumes:
      - ./docker/postgresql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    depends_on:
      - postgresql